/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.witherxee.petclinic.ui;

import com.witherxee.petclinic.controller.CustomerController;
import com.witherxee.petclinic.model.Customer;
import java.awt.*;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author witherxee
 */
public class CustomerPanel extends javax.swing.JPanel {

    private CustomerController controller;
    private int selectedCustomerId = -1;

    private final Color BACKGROUND = new Color(235, 241, 247);
    private final Color NAVY = new Color(32, 58, 86);
    private final Color ACCENT = new Color(55, 107, 154);
    private final Color MUTED = new Color(90, 108, 125);
    private final Color BORDER = new Color(218, 226, 235);

    /**
     * Creates new form CustomerPanel
     */
    public CustomerPanel() {
        initComponents();
        applyStyle();
        controller = new CustomerController();
        loadCustomers();
    }
    
    private void applyStyle(){
        
        styleLabel(lblName1);
        styleLabel(lblPhone1);
        styleLabel(lblEmail1);
        styleLabel(lblAddress1);
        
        styleField(txtName1);
        styleField(txtPhone1);
        styleField(txtEmail1);
        styleField(txtAddress1);
        
        btnAdd1.setBackground(ACCENT);
        btnAdd1.setForeground(Color.WHITE);

        btnUpdate1.setBackground(NAVY);
        btnUpdate1.setForeground(Color.WHITE);

        btnDelete1.setBackground(new Color(170, 75, 75));
        btnDelete1.setForeground(Color.WHITE);

        btnClear1.setBackground(new Color(235, 241, 247));
        btnClear1.setForeground(NAVY);

        btnAdd1.setFont(new Font("SansSerif", Font.BOLD, 13));
        btnUpdate1.setFont(new Font("SansSerif", Font.BOLD, 13));
        btnDelete1.setFont(new Font("SansSerif", Font.BOLD, 13));
        btnClear1.setFont(new Font("SansSerif", Font.BOLD, 13));
        
        tblCustomers.setRowHeight(30);
        tblCustomers.setFont(new Font("SansSerif", Font.PLAIN, 13));
        tblCustomers.setForeground(NAVY);
        tblCustomers.setShowGrid(false);

        tblCustomers.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 13));

        tblCustomers.getTableHeader().setForeground(NAVY);
    }
    
    private void styleLabel(javax.swing.JLabel label) {
        label.setFont(new Font("SansSerif", Font.BOLD, 13));
        label.setForeground(NAVY);
    }

    private void styleField(javax.swing.JTextField field) {
        field.setFont(new Font("SansSerif", Font.PLAIN, 13));
        field.setBorder(
            BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(210, 220, 230)),
                BorderFactory.createEmptyBorder(5, 8, 5, 8)
            )
        );
    }

    private void loadCustomers() {
        DefaultTableModel model = (DefaultTableModel) tblCustomers.getModel();

        model.setRowCount(0);

        List<Customer> customers = controller.getAllCustomers();

        for (Customer customer : customers) {
            model.addRow(new Object[]{
                customer.getId(),
                customer.getName(),
                customer.getPhoneNumber(),
                customer.getEmail(),
                customer.getAddress()
            });
        }
    }

    private void clearFields() {
        txtName1.setText("");
        txtPhone1.setText("");
        txtEmail1.setText("");
        txtAddress1.setText("");

        selectedCustomerId = -1;
        tblCustomers.clearSelection();
    }

    private boolean validateFields() {
        if (txtName1.getText().trim().isEmpty()
                || txtPhone1.getText().trim().isEmpty()
                || txtEmail1.getText().trim().isEmpty()
                || txtAddress1.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please fill all fields.",
                    "Validation",
                    JOptionPane.WARNING_MESSAGE);

            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        formPanel1 = new javax.swing.JPanel();
        lblName1 = new javax.swing.JLabel();
        lblPhone1 = new javax.swing.JLabel();
        lblEmail1 = new javax.swing.JLabel();
        lblAddress1 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        txtPhone1 = new javax.swing.JTextField();
        txtEmail1 = new javax.swing.JTextField();
        txtAddress1 = new javax.swing.JTextField();
        btnAdd1 = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        btnClear1 = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        lblTableTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomers = new javax.swing.JTable();

        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(32, 58, 86));
        lblTitle.setText("Customer Management");

        lblSubtitle.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(90, 108, 125));
        lblSubtitle.setText("Manage pet owners and their contact information.");

        formPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblName1.setText("Name");

        lblPhone1.setText("Phone");

        lblEmail1.setText("Email");

        lblAddress1.setText("Address");

        btnAdd1.setText("Add");
        btnAdd1.addActionListener(this::btnAdd1ActionPerformed);

        btnUpdate1.setText("Update");
        btnUpdate1.addActionListener(this::btnUpdate1ActionPerformed);

        btnDelete1.setText("Delete");
        btnDelete1.addActionListener(this::btnDelete1ActionPerformed);

        btnClear1.setText("Clear");
        btnClear1.addActionListener(this::btnClear1ActionPerformed);

        javax.swing.GroupLayout formPanel1Layout = new javax.swing.GroupLayout(formPanel1);
        formPanel1.setLayout(formPanel1Layout);
        formPanel1Layout.setHorizontalGroup(
            formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName1)
                    .addComponent(lblPhone1)
                    .addComponent(lblEmail1)
                    .addComponent(lblAddress1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanel1Layout.createSequentialGroup()
                        .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhone1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAddress1)
                            .addComponent(txtEmail1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdate1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(btnDelete1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(txtName1)))
        );
        formPanel1Layout.setVerticalGroup(
            formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName1)
                    .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail1))
                .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                    .addGroup(formPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formPanel1Layout.createSequentialGroup()
                                .addComponent(lblAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtAddress1))))
                .addContainerGap())
        );

        tablePanel.setBackground(new java.awt.Color(255, 255, 255));

        lblTableTitle.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        lblTableTitle.setForeground(new java.awt.Color(32, 58, 86));
        lblTableTitle.setText("Registered Customers");

        tblCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Phone", "Email", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCustomers.setRowHeight(30);
        tblCustomers.setShowGrid(false);
        tblCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustomers);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTableTitle)
            .addComponent(jScrollPane1)
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addComponent(lblTableTitle)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addComponent(lblSubtitle))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitle)
                .addGap(5, 5, 5)
                .addComponent(lblSubtitle)
                .addGap(20, 20, 20)
                .addComponent(formPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        if (!validateFields()) {
            return;
        }

        Customer customer = new Customer(
                0,
                txtName1.getText().trim(),
                txtPhone1.getText().trim(),
                txtEmail1.getText().trim(),
                txtAddress1.getText().trim()
        );

        controller.addCustomer(customer);
        loadCustomers();
        clearFields();

        JOptionPane.showMessageDialog(
                this,
                "Customer added successfully.",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        if (selectedCustomerId == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Please select a customer.",
                    "Validation",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!validateFields()) {
            return;
        }

        Customer customer = new Customer(
                selectedCustomerId,
                txtName1.getText().trim(),
                txtPhone1.getText().trim(),
                txtEmail1.getText().trim(),
                txtAddress1.getText().trim()
        );

        controller.updateCustomer(customer);
        loadCustomers();
        clearFields();

        JOptionPane.showMessageDialog(
                this,
                "Customer updated successfully.",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        if (selectedCustomerId == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Please select a customer.",
                    "Validation",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int result = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete this customer?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.YES_OPTION) {
            controller.deleteCustomer(selectedCustomerId);
            loadCustomers();
            clearFields();

            JOptionPane.showMessageDialog(
                    this,
                    "Customer deleted successfully.",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tblCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomersMouseClicked

        int row = tblCustomers.getSelectedRow();

        if (row >= 0) {
            selectedCustomerId = Integer.parseInt(
                    tblCustomers.getValueAt(row, 0).toString());

            txtName1.setText(
                    tblCustomers.getValueAt(row, 1).toString());

            txtPhone1.setText(
                    tblCustomers.getValueAt(row, 2).toString());

            txtEmail1.setText(
                    tblCustomers.getValueAt(row, 3).toString());

            txtAddress1.setText(
                    tblCustomers.getValueAt(row, 4).toString());
        }
    }//GEN-LAST:event_tblCustomersMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JPanel formPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblPhone1;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTableTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JTable tblCustomers;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtPhone1;
    // End of variables declaration//GEN-END:variables
}
