/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.witherxee.petclinic.ui;

import com.witherxee.petclinic.controller.VeterinarianController;
import com.witherxee.petclinic.model.Veterinarian;

import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author witherxee
 */
public class VeterinarianPanel extends javax.swing.JPanel {
    
    private final VeterinarianController controller = new VeterinarianController();

    private int selectedVeterinarianId = -1;

    private final Color BACKGROUND = new Color(235, 241, 247);
    private final Color NAVY = new Color(32, 58, 86);
    private final Color ACCENT = new Color(55, 107, 154);
    private final Color MUTED = new Color(90, 108, 125);

    /**
     * Creates new form VeterinarianPanel
     */
    public VeterinarianPanel() {
        initComponents();
        applyStyle();
        loadVeterinarians();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        lblTableTitle = new javax.swing.JLabel();
        tblVeterinarians = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(32, 58, 86));
        lblTitle.setText("Veterinarian Managment");

        lblSubtitle.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(90, 108, 125));
        lblSubtitle.setText("Manage the Veterinarians and their details.");

        formPanel.setBackground(new java.awt.Color(255, 255, 255));
        formPanel.setMinimumSize(new java.awt.Dimension(0, 0));

        lblName.setText("Full Name");

        lblPhone.setText("Phone Number");

        lblEmail.setText("Email");

        lblAddress.setText("Address");

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(lblAddress)
                            .addComponent(lblName)
                            .addComponent(lblPhone)
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAddress)
                                    .addGroup(formPanelLayout.createSequentialGroup()
                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 15, Short.MAX_VALUE))))))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEmail)
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtName))
                            .addComponent(txtPhone))))
                .addGap(38, 38, 38))
        );
        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        tablePanel.setBackground(new java.awt.Color(255, 255, 255));

        lblTableTitle.setFont(new java.awt.Font("SansSerif", 1, 17)); // NOI18N
        lblTableTitle.setForeground(new java.awt.Color(32, 58, 86));
        lblTableTitle.setText("Registered Veterinarians");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Phone", "Email", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        tblVeterinarians.setViewportView(jTable1);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addComponent(lblTableTitle)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblVeterinarians)
                .addContainerGap())
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addComponent(lblTableTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tblVeterinarians, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSubtitle)
                    .addComponent(lblTitle)
                    .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitle)
                .addGap(18, 18, 18)
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void applyStyle() {
    setBackground(BACKGROUND);

    formPanel.setBorder(
        BorderFactory.createLineBorder(new Color(218, 226, 235))
    );

    tablePanel.setBorder(
        BorderFactory.createLineBorder(new Color(218, 226, 235))
    );

    styleLabel(lblName);
    styleLabel(lblPhone);
    styleLabel(lblEmail);
    styleLabel(lblAddress);

    lblTitle.setFont(new Font("SansSerif", Font.BOLD, 28));
    lblTitle.setForeground(NAVY);

    lblSubtitle.setFont(new Font("SansSerif", Font.PLAIN, 14));
    lblSubtitle.setForeground(MUTED);

    lblTableTitle.setFont(new Font("SansSerif", Font.BOLD, 17));
    lblTableTitle.setForeground(NAVY);

    styleField(txtName);
    styleField(txtPhone);
    styleField(txtEmail);
    styleField(txtAddress);

    btnAdd.setBackground(ACCENT);
    btnAdd.setForeground(Color.WHITE);

    btnUpdate.setBackground(NAVY);
    btnUpdate.setForeground(Color.WHITE);

    btnDelete.setBackground(new Color(170, 75, 75));
    btnDelete.setForeground(Color.WHITE);

    btnClear.setBackground(new Color(235, 241, 247));
    btnClear.setForeground(NAVY);

    btnAdd.setFont(new Font("SansSerif", Font.BOLD, 13));
    btnUpdate.setFont(new Font("SansSerif", Font.BOLD, 13));
    btnDelete.setFont(new Font("SansSerif", Font.BOLD, 13));
    btnClear.setFont(new Font("SansSerif", Font.BOLD, 13));

    jTable1.setRowHeight(30);
    jTable1.setFont(new Font("SansSerif", Font.PLAIN, 13));
    jTable1.setForeground(NAVY);
    jTable1.setShowGrid(false);

    jTable1.getTableHeader().setFont(
        new Font("SansSerif", Font.BOLD, 13)
    );

    jTable1.getTableHeader().setForeground(NAVY);
}

    private void styleLabel(javax.swing.JLabel label) {
        label.setFont(new Font("SansSerif", Font.BOLD, 13));
        label.setForeground(NAVY);
    }

    private void styleField(javax.swing.JTextField field) {
        field.setFont(new Font("SansSerif", Font.PLAIN, 13));
        field.setBorder(
            BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(210, 220, 230)),
                BorderFactory.createEmptyBorder(5, 8, 5, 8)
            )
        );
    }
    
    private void clearFields() {
        txtName.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtAddress.setText("");

        selectedVeterinarianId = -1;

        jTable1.clearSelection();
    }
    
    private void loadVeterinarians() {
    List<Veterinarian> veterinarians = controller.getAllVeterinarians();

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    for (Veterinarian veterinarian : veterinarians) {
        model.addRow(new Object[]{
            veterinarian.getId(),
            veterinarian.getName(),
            veterinarian.getPhoneNumber(),
            veterinarian.getEmail(),
            veterinarian.getAddress()
        });
    }
}
    
    private boolean validateFields() {
    if (txtName.getText().trim().isEmpty()
            || txtPhone.getText().trim().isEmpty()
            || txtEmail.getText().trim().isEmpty()
            || txtAddress.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(
            this,
            "Please fill in all fields.",
            "Validation Error",
            JOptionPane.WARNING_MESSAGE
        );

        return false;
    }

    return true;
}
    
    private Veterinarian getVeterinarianFromFields() {
        Veterinarian veterinarian = new Veterinarian();

        veterinarian.setId(selectedVeterinarianId);
        veterinarian.setName(txtName.getText().trim());
        veterinarian.setPhoneNumber(txtPhone.getText().trim());
        veterinarian.setEmail(txtEmail.getText().trim());
        veterinarian.setAddress(txtAddress.getText().trim());

        return veterinarian;
    }
    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (selectedVeterinarianId == -1) {
            JOptionPane.showMessageDialog(this, "Please select a veterinarian first.");
            return;
        }

        controller.deleteVeterinarian(selectedVeterinarianId);

        JOptionPane.showMessageDialog(this, "Veterinarian deleted successfully.");

        clearFields();
        loadVeterinarians();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (!validateFields()) {
            return;
        }

        Veterinarian veterinarian = getVeterinarianFromFields();

        controller.addVeterinarian(veterinarian);

        JOptionPane.showMessageDialog(this, "Veterinarian added successfully.");

        clearFields();
        loadVeterinarians();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (selectedVeterinarianId == -1) {
            JOptionPane.showMessageDialog(this, "Please select a veterinarian first.");
            return;
        }

        if (!validateFields()) {
            return;
        }

        controller.updateVeterinarian(getVeterinarianFromFields());

        JOptionPane.showMessageDialog(this, "Veterinarian updated successfully.");

        clearFields();
        loadVeterinarians();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();

        if (row == -1) {
            return;
        }

        selectedVeterinarianId = (int) jTable1.getValueAt(row, 0);
        txtName.setText(jTable1.getValueAt(row, 1).toString());
        txtPhone.setText(jTable1.getValueAt(row, 2).toString());
        txtEmail.setText(jTable1.getValueAt(row, 3).toString());
        txtAddress.setText(jTable1.getValueAt(row, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel formPanel;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTableTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JScrollPane tblVeterinarians;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
